"""LiveWell Coach as a Foundry hosted agent: the Lab 4 sequential team behind one Responses endpoint.

    request -> resident profile -> Nutrition -> Activity -> Coach -> one evidence JSON reply

The team is the sequential workflow of content/assets/lab4_multiagent.py (section 4). Instructions, tool
connections and the reply schema come from livewell.json, generated by scripts/gen-schemas.py from the same
sources as the lab scripts. Every model call goes to the project's deployment (livewell-guardrails), and
the agent itself carries the same policy through the `policies` block in azure.yaml.

Run locally:  azd ai agent run livewell-workshop-hosted --no-client   (see README.md)
"""
from __future__ import annotations

import functools
import json
import os
import pathlib

import httpx
from agent_framework import Agent, Executor, Message, WorkflowContext, agent_middleware, handler
from agent_framework.foundry import FoundryChatClient
from agent_framework.orchestrations import SequentialBuilder
from agent_framework_foundry_hosting import ResponsesHostServer
from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv

load_dotenv()
SPEC = json.loads((pathlib.Path(__file__).with_name("livewell.json")).read_text(encoding="utf-8"))


def project_endpoint() -> str:
    # FOUNDRY_PROJECT_ENDPOINT is injected by the hosting platform; AZURE_AI_PROJECT_ENDPOINT comes from azd.
    return os.environ.get("FOUNDRY_PROJECT_ENDPOINT") or os.environ["AZURE_AI_PROJECT_ENDPOINT"]


@functools.lru_cache(maxsize=None)
def connection_target(name: str) -> str:
    """MCP server URL of a project connection (the Responses API needs it next to the connection id)."""
    with AIProjectClient(endpoint=project_endpoint(), credential=DefaultAzureCredential()) as project:
        return project.connections.get(name).target


def mcp_tool(client: FoundryChatClient, key: str):
    tool = SPEC["tools"][key]
    return client.get_mcp_tool(name=tool["label"], url=connection_target(tool["connection"]),
                               project_connection_id=tool["connection"], approval_mode="never_require",
                               allowed_tools=tool["allowed_tools"])


def profile_summary(p: dict) -> str:
    """Same line as livewell_common.profile_summary; never includes the resident_id."""
    return (f"Resident profile: age band {p['age_band']}, lives in {p['planning_area']} ({p['region']} region, "
            f"hazy today: {'yes' if p['region_is_hazy'] else 'no'}), screening risk {p['screening_risk']}, "
            f"conditions: {', '.join(p.get('conditions') or ['none'])}, about {p['avg_daily_steps']:.0f} steps a day.")


class ResidentProfile(Executor):
    """First step: put the signed-in resident's profile in front of the latest request. The activities
    server only serves /profile/me (the session resident), as for the Navigator profile tool."""

    def __init__(self, url: str):
        super().__init__(id="resident_profile")
        self.url = url

    @handler
    async def add_profile(self, conversation: list[Message], ctx: WorkflowContext[list[Message]]) -> None:
        async with httpx.AsyncClient(timeout=60) as http:  # the activities app may be scaled to zero
            response = await http.get(self.url)
            response.raise_for_status()
        last = max((i for i, m in enumerate(conversation) if m.role == "user"), default=None)
        if last is not None:
            request = conversation[last]
            conversation = [*conversation[:last],
                            Message("user", [f"{profile_summary(response.json())}\n\n{request.text}"]),
                            *conversation[last + 1:]]
        await ctx.send_message(conversation)


@agent_middleware
async def text_only(context, call_next):
    """Each agent sees earlier answers as plain text: another agent's MCP call items can break its model call."""
    context.messages[:] = [Message(m.role, [m.text], author_name=m.author_name) for m in context.messages if m.text]
    await call_next()


def build_agent():
    client = FoundryChatClient(project_endpoint=project_endpoint(),
                               model=os.environ["AZURE_AI_MODEL_DEPLOYMENT_NAME"],
                               credential=DefaultAzureCredential())
    tools = {key: mcp_tool(client, key) for key in SPEC["tools"]}
    fmt = SPEC["response_format"]

    def agent(name: str, **options) -> Agent:
        spec = SPEC["agents"][name]
        return Agent(client, spec["instructions"], name=name, description=spec["description"],
                     tools=[tools[t] for t in spec["tools"]], middleware=[text_only],
                     default_options={"store": False, **options})

    coach = agent("coach", response_format={"type": "json_schema", "json_schema": {**fmt, "strict": True}})
    profile_url = connection_target(SPEC["tools"]["activities"]["connection"]).rsplit("/mcp", 1)[0] + "/profile/me"
    workflow = SequentialBuilder(participants=[ResidentProfile(profile_url), agent("nutrition"), agent("activity"),
                                               coach]).build()
    return workflow.as_agent(name="livewell-workshop-hosted")


def main() -> None:
    ResponsesHostServer(build_agent()).run()


if __name__ == "__main__":
    main()
