#!/usr/bin/env python3
"""Select the per-environment parameter file and make `azd provision` self-contained.

Run by scripts/provision.sh BEFORE `azd provision`, and again as the azd preprovision hook (--hook).

1. Copies infra/env/<AZURE_ENV_NAME>.bicepparam -> infra/main.bicepparam (gitignored), fixing the
   `using` path, because azd only reads infra/main.bicepparam.
2. Fills AZURE_PRINCIPAL_ID / AZURE_PRINCIPAL_TYPE in the azd env from the signed-in az identity
   if they are missing (facilitator RBAC in the template), and pins BUDGET_START_DATE.
3. Creates the resource group (idempotent) with the workshop tags, because the template is
   resource-group scoped.

azd resolves parameters BEFORE the preprovision hook runs, so in --hook mode any change made in
steps 1-2 stops the run with "re-run" (a stale file can never deploy the wrong environment).

Standard library only; ASCII output. Exit code != 0 stops `azd provision`.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INFRA = ROOT / "infra"


def run(cmd: list[str], check: bool = True) -> str:
    exe = shutil.which(cmd[0]) or cmd[0]
    proc = subprocess.run([exe, *cmd[1:]], capture_output=True, text=True)
    if check and proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"[select-params] command failed: {' '.join(cmd)}")
    return proc.stdout.strip()


def load_azd_env() -> None:
    """Outside azd hooks, pull the selected azd env's values into os.environ."""
    out = run(["azd", "env", "get-values"], check=False)
    for line in out.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip().strip('"'))

def main() -> int:
    hook_mode = "--hook" in sys.argv[1:]
    env = os.environ.get("AZURE_ENV_NAME", "").strip()
    if not env:
        env = run(["azd", "env", "get-value", "AZURE_ENV_NAME"], check=False)
        if not env or " " in env:
            print("[select-params] AZURE_ENV_NAME is not set (run inside azd, or `azd env select <env>`).")
            return 1
        load_azd_env()
    src = INFRA / "env" / f"{env}.bicepparam"
    if not src.exists():
        choices = ", ".join(p.stem for p in sorted((INFRA / "env").glob("*.bicepparam")))
        print(f"[select-params] no parameter file for env '{env}'. Known envs: {choices}")
        return 1

    text = src.read_text(encoding="utf-8")
    text, count = re.subn(r"^using\s+'\.\./main\.bicep'", "using 'main.bicep'", text, flags=re.M)
    if count != 1:
        print(f"[select-params] {src.name} must start with: using '../main.bicep'")
        return 1
    header = f"// GENERATED by scripts/select-params.py from infra/env/{env}.bicepparam. Do not edit.\n"
    desired = header + text
    target = INFRA / "main.bicepparam"
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if current != desired:
        target.write_text(desired, encoding="utf-8", newline="\n")
        print(f"[select-params] infra/main.bicepparam <- infra/env/{env}.bicepparam (regenerated)")
        if hook_mode:
            # azd resolved parameters before this hook ran, so this run would use stale/missing values.
            print("[select-params] Parameters changed after azd read them. Re-run the same command "
                  "(or use scripts/provision.sh, which runs this step first).")
            return 1
    else:
        print(f"[select-params] infra/main.bicepparam matches infra/env/{env}.bicepparam")

    if os.environ.get("AZURE_PRINCIPAL_ID"):
        print("[select-params] AZURE_PRINCIPAL_ID already set")
    else:
        account = json.loads(run(["az", "account", "show", "-o", "json"]))
        if account.get("user", {}).get("type") == "servicePrincipal":
            pid = run(["az", "ad", "sp", "show", "--id", account["user"]["name"], "--query", "id", "-o", "tsv"])
            ptype = "ServicePrincipal"
        else:
            pid = run(["az", "ad", "signed-in-user", "show", "--query", "id", "-o", "tsv"])
            ptype = "User"
        run(["azd", "env", "set", "AZURE_PRINCIPAL_ID", pid])
        run(["azd", "env", "set", "AZURE_PRINCIPAL_TYPE", ptype])
        os.environ["AZURE_PRINCIPAL_ID"] = pid
        print(f"[select-params] AZURE_PRINCIPAL_ID set for the signed-in {ptype.lower()}")
        if hook_mode:
            print("[select-params] Principal added after azd read parameters. Re-run the same command.")
            return 1

    # Pin the budget start month for the life of this environment (a budget cannot move its start date).
    # When azd has already read an empty value, main.bicep falls back to the same current month.
    if os.environ.get("BUDGET_START_DATE"):
        print(f"[select-params] BUDGET_START_DATE={os.environ['BUDGET_START_DATE']}")
    else:
        start = datetime.now(timezone.utc).strftime("%Y-%m-01")
        run(["azd", "env", "set", "BUDGET_START_DATE", start])
        print(f"[select-params] BUDGET_START_DATE pinned to {start}")

    rg = os.environ.get("AZURE_RESOURCE_GROUP", "").strip()
    location = os.environ.get("AZURE_LOCATION", "swedencentral").strip()
    sub = os.environ.get("AZURE_SUBSCRIPTION_ID", "").strip()
    if not rg:
        print("[select-params] AZURE_RESOURCE_GROUP is not set (expected rg-livewell-workshop-<env>).")
        return 1
    cmd = ["az", "group", "create", "-n", rg, "-l", location, "--tags", "workshop=livewell",
           f"env={env}", f"azd-env-name={env}", "-o", "none"]
    if sub:
        cmd += ["--subscription", sub]
    run(cmd)
    print(f"[select-params] resource group {rg} ready in {location}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
