#!/usr/bin/env python3
"""Write the live profile OpenAPI spec into the Lab 3 copy-and-paste block (Navigator and portal pages).

Participants copy the spec from the lab page instead of opening the spec URL. The spec has to carry the
environment's server address, because the OpenAPI tool calls it, so this block is the one place a lab page holds an
endpoint (AGENTS.md; scripts/check-content.py allows it only inside the markers, only on the Lab 3 pages, and only
as an OpenAPI 3 document). Participants read the pages on GitHub, so re-run this and commit and push the two pages
whenever the activities app's address changes (a new azd environment, or a provision after teardown).

    python scripts/sync-openapi-block.py [env]           # default: the selected azd env
    python scripts/sync-openapi-block.py [env] --check   # exit 1 if a page does not match the live spec
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGES = [ROOT / "content" / "labs" / "lab-03.md", ROOT / "content" / "labs" / "lab-03-portal.md"]
BLOCK_RE = re.compile(r"^([ \t]*)<!-- openapi-spec:begin\b[^\n]*-->\n.*?^[ \t]*<!-- openapi-spec:end -->[ \t]*$",
                      re.M | re.S)


def say(msg: str) -> None:
    print(f"[sync-openapi-block] {msg}", flush=True)


def selected_env() -> str:
    try:
        out = subprocess.run(["azd", "env", "list", "--output", "json"], capture_output=True, text=True,
                             shell=os.name == "nt", timeout=60).stdout
        return next((e["Name"] for e in json.loads(out or "[]") if e.get("IsDefault")), "")
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return ""


def env_values(env: str) -> dict[str, str]:
    path = ROOT / ".azure" / env / ".env"
    if not path.exists():
        raise SystemExit(f"[sync-openapi-block] {path.relative_to(ROOT)} not found (run scripts/provision.sh {env})")
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip().strip('"')
    return values


def fetch_spec(url: str) -> dict:
    """The app scales to zero when idle, so the first request can take about a minute."""
    last = ""
    for attempt in range(3):
        try:
            with urllib.request.urlopen(url, timeout=90) as r:
                return json.loads(r.read().decode("utf-8"))
        except (urllib.error.URLError, TimeoutError, ValueError) as e:
            last = str(e)
            time.sleep(5 * (attempt + 1))
    raise SystemExit(f"[sync-openapi-block] could not read {url}: {last}")


def validate(spec: dict, url: str) -> None:
    servers = [s.get("url", "") for s in spec.get("servers") or []]
    op = (((spec.get("paths") or {}).get("/profile/{resident_id}") or {}).get("get") or {}).get("operationId")
    host = urllib.parse.urlsplit(url).netloc
    problems = []
    if not str(spec.get("openapi", "")).startswith("3."):
        problems.append("not an OpenAPI 3 document")
    if not servers or urllib.parse.urlsplit(servers[0]).netloc != host:
        problems.append(f"servers {servers} do not point at {host}")
    if op != "get_citizen_profile":
        problems.append(f"operationId {op!r}, expected 'get_citizen_profile'")
    if problems:
        raise SystemExit(f"[sync-openapi-block] {url}: " + "; ".join(problems))


def render(spec: dict, indent: str, env: str) -> str:
    lines = [f"<!-- openapi-spec:begin (generated by scripts/sync-openapi-block.py {env}; do not edit) -->", "```json",
             *json.dumps(spec, indent=2, ensure_ascii=False).splitlines(), "```", "<!-- openapi-spec:end -->"]
    return "\n".join(indent + line for line in lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("env", nargs="?", help="azd environment (default: AZURE_ENV_NAME or the selected one)")
    ap.add_argument("--check", action="store_true", help="report only; exit 1 if a page is out of date")
    args = ap.parse_args()

    env = args.env or os.environ.get("AZURE_ENV_NAME", "") or selected_env()
    if not env:
        raise SystemExit("[sync-openapi-block] no environment: pass it (sponsor | mcaps) or azd env select one")
    values = env_values(env)
    url = values.get("PROFILE_OPENAPI_URL")
    if not url:
        raise SystemExit("[sync-openapi-block] PROFILE_OPENAPI_URL missing in the azd env: run scripts/connect-tools.py")
    spec = fetch_spec(url)
    validate(spec, url)

    stale = 0
    for page in PAGES:
        rel = page.relative_to(ROOT).as_posix()
        text = page.read_text(encoding="utf-8")
        match = BLOCK_RE.search(text)
        if not match:
            raise SystemExit(f"[sync-openapi-block] {rel}: no <!-- openapi-spec:begin --> ... end block")
        new = text[:match.start()] + render(spec, match.group(1), env) + text[match.end():]
        if new == text:
            say(f"{rel}: in sync with {env}")
            continue
        stale += 1
        if args.check:
            say(f"{rel}: OUT OF DATE for {env}: python scripts/sync-openapi-block.py {env}, then commit and push")
        else:
            page.write_text(new, encoding="utf-8", newline="\n")
            say(f"{rel}: updated from {url} (commit and push it: participants read the page on GitHub)")
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
